version: 2
executorType: docker
containerInfo:
  - image: ubuntu:14.04
    cmd: ["/bin/bash"]
  - image: mongo:2.6.8
    cmd: [mongod, --smallfiles]

stages:
  build:
    workDir: /root/workDir

    steps:
      - type: shell
        name: Initialize Working Directory
        pwd: /
        command: |
          mkdir /root/workDir

      - type: shell
        name: Install packages
        command: |
          apt-get update -qq && apt-get install -qqy git curl openjdk-8-jdk

      - type: shell
        name: Install Docker Client
        command: |
          echo "test"
          curl -L -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-1.12.3.tgz
          tar -xz -C /tmp -f /tmp/docker.tgz
          mv /tmp/docker/docker* /usr/bin/

          curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
          chmod +x  /usr/bin/docker-compose

      - type: setup-docker-engine
      - type: shell
        name: Verify Docker Works
        command: |
          docker --version
          docker run hello-world

      - type: checkout

      - type: shell
        name: get infos
        shell: /bin/bash
        command: pwd && git --version && java -version && ls -al

      - type: shell
        name: Gradle build
        shell: /bin/bash
        command: ./gradlew --stacktrace --info --console=plain version
