version: 2
executorType: docker
containerInfo:
  - image: cloudbees/java-build-tools:2.0.0
    cmd: ["/bin/bash"]
  - image: mongo:2.6.8
    cmd: [mongod, --smallfiles]

stages:
  build:
    workDir: ~/workdir
    steps:
      - type: checkout

      - type: shell
        name: Gradle build
        shell: /bin/bash
        command: gradlew --stacktrace --info --console=plain version
