version: 2
executorType: docker
containerInfo:
  - image: ubuntu:14.04
    cmd: ["/bin/bash"]
  - image: mongo:2.6.8
    cmd: [mongod, --smallfiles]

stages:
  prepare:
    steps:
      - type: shell
        name: update apt package cache
        shell: /bin/bash
        command: sudo apt-get update

      - type: shell
        name: install packages
        shell: /bin/bash
        command: |
          sudo apt-get install -y git --no-install-recommends
          linux-image-extra-$(uname -r) linux-image-extra-virtual
          apt-transport-https ca-certificates curl software-properties-common

      - type: shell
        name: add docker apt repo
        shell: /bin/bash
        command: curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -

      - type: shell
        name: add docker apt repo
        shell: /bin/bash
        command: sudo add-apt-repository "deb https://apt.dockerproject.org/repo/ ubuntu-$(lsb_release -cs) main"

      - type: shell
        name: update apt package cache
        shell: /bin/bash
        command: sudo apt-get update

      - type: shell
        name: install docker
        shell: /bin/bash
        command: sudo apt-get -y install docker-engine

  build:
    workDir: ~/workdir
    steps:
      - type: checkout

      - type: shell
        name: get infos
        shell: /bin/bash
        command: pwd && git --version && java -version && ls -al

      - type: shell
        name: Gradle build
        shell: /bin/bash
        command: ./gradlew --stacktrace --info --console=plain version
